baseURL: https://rustamjafar.com/
defaultContentLanguage: multilang
defaultContentLanguageInSubdir: true
title: rustamjafar
theme: rstscheme
uglyURLs: false
publishDir: docs
languages:
  multilang:
    disabled: false
    contentDir: content/multilang
    languageCode: multilang
    languageName: multi
    weight: 10
  ar:
    disabled: false
    contentDir: content/ar
    languageCode: ar
    languageDirection: rtl
    languageName: arabic
    weight: 30
    params:
      intention: >-
        بسم الله الرحمن الرحيم
      contact: >-
        اتصل بي
  en:
    disabled: false
    contentDir: content/en
    languageCode: en-US
    languageDirection: ltr
    languageName: english
    weight: 20
    params:
      intention: >-
        in the name of god, the most beneficent, the most merciful
      contact: >-
        rst.jafar@gmail.com
  ru:
    disabled: false
    contentDir: content/ru
    languageCode: ru-RU
    languageDirection: ltr
    languageName: russian
    weight: 40
    params:
      intention: >-
        во имя бога, милостивого, милующего
      contact: >-
        свяжитесь со мной
# remove hugo version mention in generated html
disableHugoGeneratorInject: true

# this is copied from the web for asciidoc support
security:
  enableInlineShortcodes: false
  exec:
    allow:
    - ^(dart-)?sass(-embedded)?$
    - ^go$
    - ^npx$
    - ^postcss$
    - ^tailwindcss$
    - ^asciidoctor$
  osEnv:
    - (?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+|(XDG_CONFIG_)?HOME|USERPROFILE|SSH_AUTH_SOCK|DISPLAY|LANG|SYSTEMDRIVE)$
  funcs:
    getenv:
    - ^HUGO_
    - ^CI$
  http:
    mediaTypes: null
    methods:
    - (?i)GET|POST
    urls:
    - .*
markup:
  asciidocExt:
    attributes: {}
    backend: html5
    extensions: []
    failureLevel: fatal
    noHeaderOrFooter: true
    preserveTOC: true
    safeMode: unsafe
    sectionNumbers: false
    trace: false
    verbose: false
    workingFolderCurrent: false
