name: github pages

on:
    branches:
      - main
  workflow_dispatch:

jobs:
  rstpage:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.110.0'

      - name: Build
        run: hugo --minify --config config.yaml

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      - uses: geekyeggo/delete-artifact@v5
        with:
          name: |
            github-pages
