name: github pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  runs-on: ubuntu-latest
  steps:
    - name: Build
      run: hugo --minify

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public

    - uses: geekyeggo/delete-artifact@v5
      with:
          name: |
            github-pages
